"""Subcontractor Profile Report — "Firma Kartviziti" (Faz 1.3.3).

Aggregates every signal we have on a subcontractor — contracts, payments,
contract documents (extracted_data) and risk score — into a single distilled
report. When an Anthropic API key is configured, the narrative sections are
generated by Claude; otherwise a rule-based fallback produces plausible
copy so the frontend can be developed and demoed without LLM access.

The shape of the response is `SubcontractorProfileReport` (see schemas).
"""
from __future__ import annotations

import json
from collections import Counter, defaultdict
from datetime import datetime, timezone
from decimal import Decimal
from typing import Any

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.core.config import settings
from app.models.subcontractor import (
    ContractDocument,
    ContractStatus,
    PaymentStatus,
    Subcontractor,
    SubcontractorContract,
    SubcontractorPayment,
)
from app.schemas.subcontractor import (
    PenaltyPattern,
    ProfileSection,
    SubcontractorProfileReport,
    TimelineKeyDate,
)


# =============================================================================
# Public API
# =============================================================================


async def build_profile_report(
    db: AsyncSession,
    subcontractor_id: int,
) -> SubcontractorProfileReport | None:
    """Build the consolidated profile report for a subcontractor.

    Returns None if the subcontractor doesn't exist. All other paths return a
    populated report — falling back to rule-based copy when Claude is offline.
    """
    sub = await db.get(Subcontractor, subcontractor_id)
    if sub is None:
        return None

    # ---- Contracts + payments ----
    contracts_stmt = (
        select(SubcontractorContract)
        .where(SubcontractorContract.subcontractor_id == subcontractor_id)
        .options(selectinload(SubcontractorContract.payments))
    )
    contracts = (await db.execute(contracts_stmt)).scalars().all()
    contract_ids = [c.id for c in contracts]

    # ---- Contract documents (extracted_data) ----
    docs: list[ContractDocument] = []
    if contract_ids:
        docs_stmt = select(ContractDocument).where(
            ContractDocument.contract_id.in_(contract_ids)
        )
        docs = list((await db.execute(docs_stmt)).scalars().all())

    # ---- Aggregate numbers ----
    total_value = Decimal("0")
    total_paid = Decimal("0")
    pending = Decimal("0")
    active_count = 0
    completed_count = 0
    delay_samples: list[int] = []

    for c in contracts:
        total_value += c.contract_amount or Decimal("0")
        if c.status == ContractStatus.ACTIVE:
            active_count += 1
        elif c.status == ContractStatus.COMPLETED:
            completed_count += 1

        for p in c.payments:
            if p.status == PaymentStatus.PAID:
                total_paid += p.amount or Decimal("0")
                if p.due_date and p.payment_date:
                    delay_samples.append((p.payment_date - p.due_date).days)
            elif p.status in (PaymentStatus.PENDING, PaymentStatus.APPROVED):
                pending += p.amount or Decimal("0")

    # ---- Also count LedgerEntry EXPENSE rows tied to this subcontractor.
    #      The legacy SubcontractorPayment table is rarely populated; in
    #      production the user works exclusively from the imported ledger,
    #      so we MUST sum that source too or "Paid" stays zero. ----
    from app.models.ledger_entry import LedgerEntry, LedgerEntryType
    from sqlalchemy import func as _func, select as _select

    ledger_paid = Decimal((await db.execute(
        _select(_func.coalesce(_func.sum(LedgerEntry.amount), 0)).where(
            LedgerEntry.subcontractor_id == subcontractor_id,
            LedgerEntry.entry_type == LedgerEntryType.EXPENSE,
        )
    )).scalar_one())
    total_paid += ledger_paid

    avg_delay = (
        round(sum(delay_samples) / len(delay_samples), 1) if delay_samples else None
    )

    # ---- Aggregate document-derived signals ----
    aggregated_risk_flags: list[str] = []
    timeline: list[TimelineKeyDate] = []
    penalty_counter: dict[str, list[dict[str, Any]]] = defaultdict(list)
    payment_terms_blurbs: list[str] = []
    document_summaries: list[str] = []

    for d in docs:
        ed = _safe_load_extracted(d.extracted_data)
        if not ed:
            continue

        for flag in ed.get("risk_flags", []) or []:
            if isinstance(flag, str) and flag not in aggregated_risk_flags:
                aggregated_risk_flags.append(flag)

        if isinstance(ed.get("payment_terms_summary"), str):
            payment_terms_blurbs.append(ed["payment_terms_summary"])

        if isinstance(ed.get("summary"), str):
            document_summaries.append(ed["summary"])

        for kd in ed.get("key_dates", []) or []:
            if isinstance(kd, dict) and kd.get("date") and kd.get("label"):
                timeline.append(
                    TimelineKeyDate(
                        date=str(kd["date"]),
                        label=str(kd["label"]),
                        description=kd.get("description"),
                        source_document=d.file_name,
                    )
                )

        for pc in ed.get("penalty_clauses", []) or []:
            if isinstance(pc, dict) and pc.get("trigger") and pc.get("penalty_type"):
                key = f"{pc['penalty_type']}::{pc['trigger'][:60].lower()}"
                penalty_counter[key].append(pc)

    timeline.sort(key=lambda kd: kd.date)

    # Convert clustered penalties into PenaltyPattern records
    penalty_patterns: list[PenaltyPattern] = []
    for cluster in penalty_counter.values():
        first = cluster[0]
        amount_repr = _humanize_penalty_amount(first)
        penalty_patterns.append(
            PenaltyPattern(
                trigger=str(first.get("trigger", "")),
                penalty_type=str(first.get("penalty_type", "")),
                typical_amount=amount_repr,
                occurrences=len(cluster),
            )
        )

    # ---- Risk score (lightweight derivation; mirrors insight_generator logic) ----
    risk_score = _derive_risk_score(
        avg_delay=avg_delay,
        active_contracts=active_count,
        risk_flags_count=len(aggregated_risk_flags),
    )

    # ---- Narrative sections (LLM if key present, else rule-based) ----
    api_key = settings.ANTHROPIC_API_KEY.strip() if settings.ANTHROPIC_API_KEY else ""
    facts = {
        "subcontractor_name": sub.name,
        "specialization": sub.specialization,
        "rating": float(sub.rating) if sub.rating else None,
        "total_contract_value": float(total_value),
        "total_paid": float(total_paid),
        "pending_amount": float(pending),
        "active_contract_count": active_count,
        "completed_contract_count": completed_count,
        "avg_payment_delay_days": avg_delay,
        "risk_score": risk_score,
        "risk_flags": aggregated_risk_flags,
        "payment_terms_blurbs": payment_terms_blurbs[:5],
        "document_summaries": document_summaries[:5],
        "penalty_patterns": [p.model_dump() for p in penalty_patterns],
        "documents_analyzed": len(docs),
    }

    if api_key:
        sections, recommendations, source = _llm_narrative(facts, api_key)
    else:
        sections, recommendations, source = _rule_narrative(facts)

    return SubcontractorProfileReport(
        subcontractor_id=sub.id,
        subcontractor_name=sub.name,
        company_overview=sections["company_overview"],
        financial_summary=sections["financial_summary"],
        risk_profile=sections["risk_profile"],
        payment_terms_summary=sections["payment_terms_summary"],
        total_contract_value=total_value,
        total_paid=total_paid,
        pending_amount=pending,
        active_contract_count=active_count,
        completed_contract_count=completed_count,
        avg_payment_delay_days=avg_delay,
        risk_score=risk_score,
        penalty_patterns=penalty_patterns,
        key_dates_timeline=timeline,
        aggregated_risk_flags=aggregated_risk_flags,
        recommendations=recommendations,
        source=source,
        documents_analyzed=len(docs),
        generated_at=datetime.now(timezone.utc),
    )


# =============================================================================
# Helpers
# =============================================================================


def _safe_load_extracted(raw: str | None) -> dict[str, Any] | None:
    """Parse the extracted_data JSON-as-text column safely."""
    if not raw:
        return None
    try:
        parsed = json.loads(raw)
        return parsed if isinstance(parsed, dict) else None
    except (ValueError, TypeError):
        return None


def _humanize_penalty_amount(pc: dict[str, Any]) -> str | None:
    """Convert a penalty clause dict into a human-readable amount string."""
    if pc.get("percentage") is not None:
        try:
            return f"{float(pc['percentage'])}%"
        except (TypeError, ValueError):
            pass
    if pc.get("amount") is not None:
        try:
            return f"{float(pc['amount']):,.0f}"
        except (TypeError, ValueError):
            pass
    return None


def _derive_risk_score(
    *,
    avg_delay: float | None,
    active_contracts: int,
    risk_flags_count: int,
) -> int:
    """Cheap rule-based risk score on 0–100. Higher == more concerning."""
    score = 10  # baseline
    if avg_delay is not None:
        if avg_delay > 30:
            score += 35
        elif avg_delay > 15:
            score += 20
        elif avg_delay > 5:
            score += 10
    score += min(40, risk_flags_count * 8)
    if active_contracts == 0:
        score += 5  # not currently engaged → less data
    return min(100, score)


# ---- Rule-based narrative fallback ----


def _rule_narrative(facts: dict[str, Any]) -> tuple[
    dict[str, ProfileSection],
    list[str],
    str,
]:
    name = facts["subcontractor_name"]
    spec = facts.get("specialization") or "general construction"
    total_v = facts["total_contract_value"]
    paid = facts["total_paid"]
    pending = facts["pending_amount"]
    active = facts["active_contract_count"]
    completed = facts["completed_contract_count"]
    delay = facts.get("avg_payment_delay_days")
    flags = facts.get("risk_flags") or []
    docs_n = facts.get("documents_analyzed", 0)

    overview = ProfileSection(
        heading="Company Overview",
        body=(
            f"{name} specializes in {spec}. {active} active and {completed} "
            f"completed contracts on file, totalling RUB {total_v:,.0f} in "
            f"committed value. {docs_n} contract document(s) analyzed."
        ),
    )

    paid_pct = (paid / total_v * 100) if total_v else 0
    financial = ProfileSection(
        heading="Financial Summary",
        body=(
            f"RUB {paid:,.0f} paid to date ({paid_pct:.0f}% of committed). "
            f"RUB {pending:,.0f} currently pending or approved-but-unpaid."
            + (
                f" Average payment delay: {delay:.1f} days."
                if delay is not None
                else ""
            )
        ),
    )

    if flags:
        risk_body = (
            f"{len(flags)} risk signal(s) flagged across documents: "
            + ", ".join(flags[:4])
            + ("…" if len(flags) > 4 else ".")
        )
    elif facts.get("risk_score", 0) >= 50:
        risk_body = "Elevated risk score driven by payment timing patterns."
    else:
        risk_body = "No critical risk signals detected. Performance within normal range."
    risk = ProfileSection(heading="Risk Profile", body=risk_body)

    blurbs = facts.get("payment_terms_blurbs") or []
    pt_body = (
        " · ".join(blurbs[:3])
        if blurbs
        else "Payment terms not yet extracted from uploaded documents."
    )
    pt = ProfileSection(heading="Payment Terms", body=pt_body)

    recs: list[str] = []
    if delay is not None and delay > 18:
        recs.append(
            f"Average payment delay is {delay:.0f} days — flag for treasury review."
        )
    if pending > total_v * Decimal("0.30"):
        recs.append("Pending balance exceeds 30% of total — verify approval queue.")
    if facts.get("risk_score", 0) >= 60:
        recs.append("Risk score above 60 — schedule a vendor review meeting.")
    if not recs:
        recs.append("No urgent actions; continue routine monitoring.")

    return (
        {
            "company_overview": overview,
            "financial_summary": financial,
            "risk_profile": risk,
            "payment_terms_summary": pt,
        },
        recs,
        "rule",
    )


# ---- LLM narrative ----


def _llm_narrative(
    facts: dict[str, Any],
    api_key: str,
) -> tuple[dict[str, ProfileSection], list[str], str]:
    """Ask Claude for the four narrative sections + recommendations."""
    try:
        import anthropic  # type: ignore

        client = anthropic.Anthropic(api_key=api_key, timeout=settings.LLM_TIMEOUT_SECONDS)
        prompt = _build_profile_prompt(facts)
        msg = client.messages.create(
            model=settings.ANTHROPIC_MODEL,
            max_tokens=1500,
            messages=[{"role": "user", "content": prompt}],
        )
        raw = msg.content[0].text if msg.content else "{}"
        parsed = json.loads(_extract_json_block(raw))

        sections = {
            "company_overview": ProfileSection(
                heading="Company Overview",
                body=str(parsed.get("company_overview", "")).strip()
                or _rule_narrative(facts)[0]["company_overview"].body,
            ),
            "financial_summary": ProfileSection(
                heading="Financial Summary",
                body=str(parsed.get("financial_summary", "")).strip()
                or _rule_narrative(facts)[0]["financial_summary"].body,
            ),
            "risk_profile": ProfileSection(
                heading="Risk Profile",
                body=str(parsed.get("risk_profile", "")).strip()
                or _rule_narrative(facts)[0]["risk_profile"].body,
            ),
            "payment_terms_summary": ProfileSection(
                heading="Payment Terms",
                body=str(parsed.get("payment_terms_summary", "")).strip()
                or _rule_narrative(facts)[0]["payment_terms_summary"].body,
            ),
        }
        recs = parsed.get("recommendations") or []
        if not isinstance(recs, list):
            recs = []
        recs = [str(r).strip() for r in recs if str(r).strip()][:6]
        if not recs:
            recs = _rule_narrative(facts)[1]
        return sections, recs, "llm"
    except Exception:
        sections, recs, _ = _rule_narrative(facts)
        return sections, recs, "rule"


def _build_profile_prompt(facts: dict[str, Any]) -> str:
    """Render the prompt sent to Claude for the profile report."""
    return (
        "You are an executive assistant in a large-scale construction company. "
        "Given structured facts about a subcontractor, produce a SHORT, factual "
        "executive summary in JSON. No marketing language. Each section must be "
        "1–3 sentences in English (or Turkish if the source data is Turkish).\n\n"
        "Facts:\n"
        f"```json\n{json.dumps(facts, ensure_ascii=False, indent=2)}\n```\n\n"
        "Return ONLY a JSON object with this exact shape, no prose around it:\n"
        '{\n'
        '  "company_overview": "string",\n'
        '  "financial_summary": "string",\n'
        '  "risk_profile": "string",\n'
        '  "payment_terms_summary": "string",\n'
        '  "recommendations": ["string", "string", ...]   // 3-5 bullets\n'
        '}\n'
    )


def _extract_json_block(raw: str) -> str:
    """Pull the first {...} JSON object out of a model response."""
    raw = raw.strip()
    # Most direct case
    if raw.startswith("{"):
        return raw
    # Find first { and last }
    start = raw.find("{")
    end = raw.rfind("}")
    if start != -1 and end != -1 and end > start:
        return raw[start : end + 1]
    return "{}"
