"""add subcontractor tables

Revision ID: 2505503c1bea
Revises: cd00e1ca86c6
Create Date: 2026-04-26 15:07:24.386938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2505503c1bea'
down_revision: Union[str, None] = 'cd00e1ca86c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subcontractors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('specialization', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'suspended', 'blacklisted', name='subcontractor_status'), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating IS NULL OR (rating >= 0 AND rating <= 5)', name='ck_subcontractors_rating_range'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcontractors_created_by'), 'subcontractors', ['created_by'], unique=False)
    op.create_index(op.f('ix_subcontractors_id'), 'subcontractors', ['id'], unique=False)
    op.create_index(op.f('ix_subcontractors_name'), 'subcontractors', ['name'], unique=False)
    op.create_index(op.f('ix_subcontractors_specialization'), 'subcontractors', ['specialization'], unique=False)
    op.create_index(op.f('ix_subcontractors_status'), 'subcontractors', ['status'], unique=False)
    op.create_index('ix_subcontractors_tax_id_lower', 'subcontractors', [sa.text('lower(tax_id)')], unique=True, postgresql_where=sa.text('tax_id IS NOT NULL'))
    op.create_table('subcontractor_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subcontractor_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('contract_number', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('contract_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'completed', 'terminated', name='contract_status'), nullable=False),
    sa.Column('scope_of_work', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('contract_amount >= 0', name='ck_subcontractor_contracts_amount_nonneg'),
    sa.CheckConstraint('end_date >= start_date', name='ck_subcontractor_contracts_date_range'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subcontractor_id'], ['subcontractors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcontractor_contracts_created_by'), 'subcontractor_contracts', ['created_by'], unique=False)
    op.create_index(op.f('ix_subcontractor_contracts_id'), 'subcontractor_contracts', ['id'], unique=False)
    op.create_index('ix_subcontractor_contracts_number_lower', 'subcontractor_contracts', [sa.text('lower(contract_number)')], unique=True, postgresql_where=sa.text('contract_number IS NOT NULL'))
    op.create_index(op.f('ix_subcontractor_contracts_project_id'), 'subcontractor_contracts', ['project_id'], unique=False)
    op.create_index(op.f('ix_subcontractor_contracts_status'), 'subcontractor_contracts', ['status'], unique=False)
    op.create_index(op.f('ix_subcontractor_contracts_subcontractor_id'), 'subcontractor_contracts', ['subcontractor_id'], unique=False)
    op.create_table('subcontractor_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('payment_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'paid', 'rejected', name='subcontractor_payment_status'), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_subcontractor_payments_amount_positive'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contract_id'], ['subcontractor_contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', 'payment_number', name='uq_subcontractor_payments_contract_paynum')
    )
    op.create_index(op.f('ix_subcontractor_payments_contract_id'), 'subcontractor_payments', ['contract_id'], unique=False)
    op.create_index(op.f('ix_subcontractor_payments_created_by'), 'subcontractor_payments', ['created_by'], unique=False)
    op.create_index(op.f('ix_subcontractor_payments_id'), 'subcontractor_payments', ['id'], unique=False)
    op.create_index(op.f('ix_subcontractor_payments_payment_date'), 'subcontractor_payments', ['payment_date'], unique=False)
    op.create_index(op.f('ix_subcontractor_payments_status'), 'subcontractor_payments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subcontractor_payments_status'), table_name='subcontractor_payments')
    op.drop_index(op.f('ix_subcontractor_payments_payment_date'), table_name='subcontractor_payments')
    op.drop_index(op.f('ix_subcontractor_payments_id'), table_name='subcontractor_payments')
    op.drop_index(op.f('ix_subcontractor_payments_created_by'), table_name='subcontractor_payments')
    op.drop_index(op.f('ix_subcontractor_payments_contract_id'), table_name='subcontractor_payments')
    op.drop_table('subcontractor_payments')
    op.drop_index(op.f('ix_subcontractor_contracts_subcontractor_id'), table_name='subcontractor_contracts')
    op.drop_index(op.f('ix_subcontractor_contracts_status'), table_name='subcontractor_contracts')
    op.drop_index(op.f('ix_subcontractor_contracts_project_id'), table_name='subcontractor_contracts')
    op.drop_index('ix_subcontractor_contracts_number_lower', table_name='subcontractor_contracts', postgresql_where=sa.text('contract_number IS NOT NULL'))
    op.drop_index(op.f('ix_subcontractor_contracts_id'), table_name='subcontractor_contracts')
    op.drop_index(op.f('ix_subcontractor_contracts_created_by'), table_name='subcontractor_contracts')
    op.drop_table('subcontractor_contracts')
    op.drop_index('ix_subcontractors_tax_id_lower', table_name='subcontractors', postgresql_where=sa.text('tax_id IS NOT NULL'))
    op.drop_index(op.f('ix_subcontractors_status'), table_name='subcontractors')
    op.drop_index(op.f('ix_subcontractors_specialization'), table_name='subcontractors')
    op.drop_index(op.f('ix_subcontractors_name'), table_name='subcontractors')
    op.drop_index(op.f('ix_subcontractors_id'), table_name='subcontractors')
    op.drop_index(op.f('ix_subcontractors_created_by'), table_name='subcontractors')
    op.drop_table('subcontractors')
    # ### end Alembic commands ###
