"""workforce module: positions, snapshots, counts

Revision ID: 70b1a888e789
Revises: 2505503c1bea
Create Date: 2026-04-28 16:08:35.975443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70b1a888e789'
down_revision: Union[str, None] = '2505503c1bea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workforce_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('direct', 'indirect', 'subcontractor', name='workforce_category'), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('name_normalized', sa.String(length=150), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'name_normalized', name='uq_workforce_position_category_name')
    )
    op.create_index('ix_workforce_position_active', 'workforce_positions', ['category', 'is_active'], unique=False)
    op.create_index(op.f('ix_workforce_positions_category'), 'workforce_positions', ['category'], unique=False)
    op.create_index(op.f('ix_workforce_positions_name_normalized'), 'workforce_positions', ['name_normalized'], unique=False)
    op.create_table('workforce_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), server_default=sa.text("'manual'"), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('total_general_staff', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_absent', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_leave_sick', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_present', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('direct_present', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('indirect_present', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('subcontractor_present', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_absent >= 0', name='ck_workforce_snapshot_absent_nonneg'),
    sa.CheckConstraint('total_general_staff >= 0', name='ck_workforce_snapshot_general_nonneg'),
    sa.CheckConstraint('total_leave_sick >= 0', name='ck_workforce_snapshot_leave_nonneg'),
    sa.CheckConstraint('total_present >= 0', name='ck_workforce_snapshot_present_nonneg'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'snapshot_date', name='uq_workforce_snapshot_project_date')
    )
    op.create_index('ix_workforce_snapshot_project_date_desc', 'workforce_snapshots', ['project_id', 'snapshot_date'], unique=False)
    op.create_index(op.f('ix_workforce_snapshots_project_id'), 'workforce_snapshots', ['project_id'], unique=False)
    op.create_index(op.f('ix_workforce_snapshots_snapshot_date'), 'workforce_snapshots', ['snapshot_date'], unique=False)
    op.create_table('workforce_counts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('general_staff', sa.Integer(), nullable=False),
    sa.Column('absent', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('leave_sick', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('present', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('absent >= 0', name='ck_workforce_count_absent_nonneg'),
    sa.CheckConstraint('general_staff >= 0', name='ck_workforce_count_general_nonneg'),
    sa.CheckConstraint('leave_sick >= 0', name='ck_workforce_count_leave_nonneg'),
    sa.CheckConstraint('present >= 0', name='ck_workforce_count_present_nonneg'),
    sa.ForeignKeyConstraint(['position_id'], ['workforce_positions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['workforce_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'position_id', name='uq_workforce_count_snapshot_position')
    )
    op.create_index(op.f('ix_workforce_counts_position_id'), 'workforce_counts', ['position_id'], unique=False)
    op.create_index(op.f('ix_workforce_counts_snapshot_id'), 'workforce_counts', ['snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workforce_counts_snapshot_id'), table_name='workforce_counts')
    op.drop_index(op.f('ix_workforce_counts_position_id'), table_name='workforce_counts')
    op.drop_table('workforce_counts')
    op.drop_index(op.f('ix_workforce_snapshots_snapshot_date'), table_name='workforce_snapshots')
    op.drop_index(op.f('ix_workforce_snapshots_project_id'), table_name='workforce_snapshots')
    op.drop_index('ix_workforce_snapshot_project_date_desc', table_name='workforce_snapshots')
    op.drop_table('workforce_snapshots')
    op.drop_index(op.f('ix_workforce_positions_name_normalized'), table_name='workforce_positions')
    op.drop_index(op.f('ix_workforce_positions_category'), table_name='workforce_positions')
    op.drop_index('ix_workforce_position_active', table_name='workforce_positions')
    op.drop_table('workforce_positions')
    # ### end Alembic commands ###
